In [1]:
# Import packages and cars dataset
import pandas as pd
cars = pd.read_csv("cars_dirty.csv")

In [2]:
# Let's take a look at the data
cars

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4.0,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,NaN,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8.0,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4.0,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4.0,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6.0,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6.0,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8.0,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,NaN,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8.0,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8.0,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8.0,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8.0,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4.0,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,NaN,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4.0,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4.0,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8.0,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8.0,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8.0,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,NaN,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4.0,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4.0,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4.0,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8.0,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,NaN,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8.0,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2
32,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2
33,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
# Data is clearly missing from the cylinder column
# Options available:
# Remove the entire column
# Fill the NaNs with the preceding number
# Fill the NaNs with the average

In [3]:
# Remove the entire column
cars2 = cars.drop(['cyl'], axis = 1)
cars2

,model,mpg,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,121.0,109,4.11,2.780,18.60,1,1,4,2
32,Volvo 142E,21.4,121.0,109,4.11,2.780,18.60,1,1,4,2
33,Volvo 142E,21.4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [4]:
# Fill the NaNs with the preceding number
#ffill = Forward fill
cars3 = cars.ffill(axis = 0)
cars3

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4.0,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,8.0,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8.0,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4.0,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4.0,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6.0,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6.0,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8.0,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8.0,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8.0,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8.0,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8.0,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8.0,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4.0,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4.0,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4.0,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4.0,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8.0,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8.0,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8.0,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8.0,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4.0,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4.0,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4.0,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8.0,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,8.0,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8.0,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2
32,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2
33,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2

In [5]:
# Fill the NaNs with the average
cars4 = cars.fillna(cars['cyl'].mean())
# Mean is 6, so this code becomes cars4 = cars.fillna(6)
cars4

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4.0,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6.0,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8.0,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4.0,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4.0,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6.0,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6.0,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8.0,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,6.0,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8.0,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8.0,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8.0,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8.0,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4.0,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,6.0,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4.0,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4.0,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8.0,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8.0,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8.0,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,6.0,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4.0,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4.0,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4.0,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8.0,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6.0,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8.0,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2
32,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2
33,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2

In [6]:
cars.tail(5)

            model   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
29   Ferrari Dino  19.7  NaN  145.0  175  3.62  2.77  15.5   0   1     5     6
30  Maserati Bora  15.0  8.0  301.0  335  3.54  3.57  14.6   0   1     5     8
31     Volvo 142E  21.4  4.0  121.0  109  4.11  2.78  18.6   1   1     4     2
32     Volvo 142E  21.4  4.0  121.0  109  4.11  2.78  18.6   1   1     4     2
33     Volvo 142E  21.4  4.0  121.0  109  4.11  2.78  18.6   1   1     4     2

In [8]:
# What about duplicates?
# cars.duplicated()
cars[cars.duplicated()]

         model   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
32  Volvo 142E  21.4  4.0  121.0  109  4.11  2.78  18.6   1   1     4     2
33  Volvo 142E  21.4  4.0  121.0  109  4.11  2.78  18.6   1   1     4     2

In [9]:
# These could be edited or removed, depending on inclination
cars5 = cars.drop_duplicates()
cars5

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6.0,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4.0,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6.0,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8.0,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,NaN,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8.0,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4.0,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4.0,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6.0,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6.0,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8.0,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,NaN,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8.0,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8.0,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8.0,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8.0,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4.0,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,NaN,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4.0,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4.0,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8.0,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8.0,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8.0,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,NaN,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4.0,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4.0,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4.0,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8.0,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,NaN,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8.0,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2

In [10]:
# String to lower
cars6 = cars
cars6['model'] = cars6['model'].str.lower()
cars6

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,mazda rx4,21.0,6.0,160.0,110,3.90,2.620,16.46,0,1,4,4
1,mazda rx4 wag,21.0,6.0,160.0,110,3.90,2.875,17.02,0,1,4,4
2,datsun 710,22.8,4.0,108.0,93,3.85,2.320,18.61,1,1,4,1
3,hornet 4 drive,21.4,6.0,258.0,110,3.08,3.215,19.44,1,0,3,1
4,hornet sportabout,18.7,8.0,360.0,175,3.15,3.440,17.02,0,0,3,2
5,valiant,18.1,NaN,225.0,105,2.76,3.460,20.22,1,0,3,1
6,duster 360,14.3,8.0,360.0,245,3.21,3.570,15.84,0,0,3,4
7,merc 240d,24.4,4.0,146.7,62,3.69,3.190,20.00,1,0,4,2
8,merc 230,22.8,4.0,140.8,95,3.92,3.150,22.90,1,0,4,2
9,merc 280,19.2,6.0,167.6,123,3.92,3.440,18.30,1,0,4,4
10,merc 280c,17.8,6.0,167.6,123,3.92,3.440,18.90,1,0,4,4
11,merc 450se,16.4,8.0,275.8,180,3.07,4.070,17.40,0,0,3,3
12,merc 450sl,17.3,NaN,275.8,180,3.07,3.730,17.60,0,0,3,3
13,merc 450slc,15.2,8.0,275.8,180,3.07,3.780,18.00,0,0,3,3
14,cadillac fleetwood,10.4,8.0,472.0,205,2.93,5.250,17.98,0,0,3,4
15,lincoln continental,10.4,8.0,460.0,215,3.00,5.424,17.82,0,0,3,4
16,chrysler imperial,14.7,8.0,440.0,230,3.23,5.345,17.42,0,0,3,4
17,fiat 128,32.4,4.0,78.7,66,4.08,2.200,19.47,1,1,4,1
18,honda civic,30.4,NaN,75.7,52,4.93,1.615,18.52,1,1,4,2
19,toyota corolla,33.9,4.0,71.1,65,4.22,1.835,19.90,1,1,4,1
20,toyota corona,21.5,4.0,120.1,97,3.70,2.465,20.01,1,0,3,1
21,dodge challenger,15.5,8.0,318.0,150,2.76,3.520,16.87,0,0,3,2
22,amc javelin,15.2,8.0,304.0,150,3.15,3.435,17.30,0,0,3,2
23,camaro z28,13.3,8.0,350.0,245,3.73,3.840,15.41,0,0,3,4
24,pontiac firebird,19.2,NaN,400.0,175,3.08,3.845,17.05,0,0,3,2
25,fiat x1-9,27.3,4.0,79.0,66,4.08,1.935,18.90,1,1,4,1
26,porsche 914-2,26.0,4.0,120.3,91,4.43,2.140,16.70,0,1,5,2
27,lotus europa,30.4,4.0,95.1,113,3.77,1.513,16.90,1,1,5,2
28,ford pantera l,15.8,8.0,351.0,264,4.22,3.170,14.50,0,1,5,4
29,ferrari dino,19.7,NaN,145.0,175,3.62,2.770,15.50,0,1,5,6
30,maserati bora,15.0,8.0,301.0,335,3.54,3.570,14.60,0,1,5,8
31,volvo 142e,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2
32,volvo 142e,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2
33,volvo 142e,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2

In [11]:
# Mapping a new column
speed = {
    4: 'Regular',
    6: 'Fast',
    8: 'Fast'
}
cars['speed'] = cars['cyl'].map(speed)
cars.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,speed
0,mazda rx4,21.0,6.0,160.0,110,3.90,2.620,16.46,0,1,4,4,Fast
1,mazda rx4 wag,21.0,6.0,160.0,110,3.90,2.875,17.02,0,1,4,4,Fast
2,datsun 710,22.8,4.0,108.0,93,3.85,2.320,18.61,1,1,4,1,Regular
3,hornet 4 drive,21.4,6.0,258.0,110,3.08,3.215,19.44,1,0,3,1,Fast
4,hornet sportabout,18.7,8.0,360.0,175,3.15,3.440,17.02,0,0,3,2,Fast

In [13]:
# Copying/subsetting a DataFrame
# Just filter and create a new DataFrame based on the filter!
cars_fast = cars[cars['speed'] == 'Fast']
cars_fast

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,speed
0,mazda rx4,21.0,6.0,160.0,110,3.90,2.620,16.46,0,1,4,4,Fast
1,mazda rx4 wag,21.0,6.0,160.0,110,3.90,2.875,17.02,0,1,4,4,Fast
3,hornet 4 drive,21.4,6.0,258.0,110,3.08,3.215,19.44,1,0,3,1,Fast
4,hornet sportabout,18.7,8.0,360.0,175,3.15,3.440,17.02,0,0,3,2,Fast
6,duster 360,14.3,8.0,360.0,245,3.21,3.570,15.84,0,0,3,4,Fast
9,merc 280,19.2,6.0,167.6,123,3.92,3.440,18.30,1,0,4,4,Fast
10,merc 280c,17.8,6.0,167.6,123,3.92,3.440,18.90,1,0,4,4,Fast
11,merc 450se,16.4,8.0,275.8,180,3.07,4.070,17.40,0,0,3,3,Fast
13,merc 450slc,15.2,8.0,275.8,180,3.07,3.780,18.00,0,0,3,3,Fast
14,cadillac fleetwood,10.4,8.0,472.0,205,2.93,5.250,17.98,0,0,3,4,Fast
15,lincoln continental,10.4,8.0,460.0,215,3.00,5.424,17.82,0,0,3,4,Fast
16,chrysler imperial,14.7,8.0,440.0,230,3.23,5.345,17.42,0,0,3,4,Fast
21,dodge challenger,15.5,8.0,318.0,150,2.76,3.520,16.87,0,0,3,2,Fast
22,amc javelin,15.2,8.0,304.0,150,3.15,3.435,17.30,0,0,3,2,Fast
23,camaro z28,13.3,8.0,350.0,245,3.73,3.840,15.41,0,0,3,4,Fast
28,ford pantera l,15.8,8.0,351.0,264,4.22,3.170,14.50,0,1,5,4,Fast
30,maserati bora,15.0,8.0,301.0,335,3.54,3.570,14.60,0,1,5,8,Fast

In [17]:
# Creating pivot tables in Pandas
cars_mpg_avg = pd.pivot_table(cars, index='cyl', values='mpg', aggfunc='mean')
# Aggfunc = "aggregation function"
cars_mpg_avg

        mpg
cyl
4.0  25.475
6.0  20.080
8.0  14.575

In [21]:
# Joins
# Re-read in cars dataframe, to overwrite any changes
# Important to know in case you get stuck!
cars = pd.read_csv("cars_dirty.csv")
cars_sales = pd.read_csv("cars_sales.csv")
cars = cars.set_index('model')
cars_joined = cars.join(cars_sales.set_index('model'), on = 'model', how = 'left')
cars_joined

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,sales
model,,,,,,,,,,,,
Mazda RX4,21.0,6.0,160.0,110,3.90,2.620,16.46,0,1,4,4,NaN
Mazda RX4 Wag,21.0,6.0,160.0,110,3.90,2.875,17.02,0,1,4,4,NaN
Datsun 710,22.8,4.0,108.0,93,3.85,2.320,18.61,1,1,4,1,NaN
Hornet 4 Drive,21.4,6.0,258.0,110,3.08,3.215,19.44,1,0,3,1,NaN
Hornet Sportabout,18.7,8.0,360.0,175,3.15,3.440,17.02,0,0,3,2,NaN
Valiant,18.1,NaN,225.0,105,2.76,3.460,20.22,1,0,3,1,NaN
Duster 360,14.3,8.0,360.0,245,3.21,3.570,15.84,0,0,3,4,NaN
Merc 240D,24.4,4.0,146.7,62,3.69,3.190,20.00,1,0,4,2,NaN
Merc 230,22.8,4.0,140.8,95,3.92,3.150,22.90,1,0,4,2,NaN
Merc 280,19.2,6.0,167.6,123,3.92,3.440,18.30,1,0,4,4,NaN
Merc 280C,17.8,6.0,167.6,123,3.92,3.440,18.90,1,0,4,4,NaN
Merc 450SE,16.4,8.0,275.8,180,3.07,4.070,17.40,0,0,3,3,NaN
Merc 450SL,17.3,NaN,275.8,180,3.07,3.730,17.60,0,0,3,3,NaN
Merc 450SLC,15.2,8.0,275.8,180,3.07,3.780,18.00,0,0,3,3,NaN
Cadillac Fleetwood,10.4,8.0,472.0,205,2.93,5.250,17.98,0,0,3,4,14777.0
Lincoln Continental,10.4,8.0,460.0,215,3.00,5.424,17.82,0,0,3,4,28388.0
Chrysler Imperial,14.7,8.0,440.0,230,3.23,5.345,17.42,0,0,3,4,35077.0
Fiat 128,32.4,4.0,78.7,66,4.08,2.200,19.47,1,1,4,1,NaN
Honda Civic,30.4,NaN,75.7,52,4.93,1.615,18.52,1,1,4,2,NaN
Toyota Corolla,33.9,4.0,71.1,65,4.22,1.835,19.90,1,1,4,1,NaN
Toyota Corona,21.5,4.0,120.1,97,3.70,2.465,20.01,1,0,3,1,NaN
Dodge Challenger,15.5,8.0,318.0,150,2.76,3.520,16.87,0,0,3,2,72204.0
AMC Javelin,15.2,8.0,304.0,150,3.15,3.435,17.30,0,0,3,2,26190.0
Camaro Z28,13.3,8.0,350.0,245,3.73,3.840,15.41,0,0,3,4,43894.0
Pontiac Firebird,19.2,NaN,400.0,175,3.08,3.845,17.05,0,0,3,2,24977.0
Fiat X1-9,27.3,4.0,79.0,66,4.08,1.935,18.90,1,1,4,1,NaN
Porsche 914-2,26.0,4.0,120.3,91,4.43,2.140,16.70,0,1,5,2,NaN
Lotus Europa,30.4,4.0,95.1,113,3.77,1.513,16.90,1,1,5,2,NaN
Ford Pantera L,15.8,8.0,351.0,264,4.22,3.170,14.50,0,1,5,4,NaN
Ferrari Dino,19.7,NaN,145.0,175,3.62,2.770,15.50,0,1,5,6,NaN
Maserati Bora,15.0,8.0,301.0,335,3.54,3.570,14.60,0,1,5,8,NaN
Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2,NaN
Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2,NaN
Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2,NaN

In [23]:
cars = pd.read_csv("cars_dirty.csv")
cars_sales = pd.read_csv("cars_sales.csv")
cars_joined = cars.join(cars_sales.set_index('model'), on = 'model', how = 'left')
cars_joined

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,sales
0,Mazda RX4,21.0,6.0,160.0,110,3.90,2.620,16.46,0,1,4,4,NaN
1,Mazda RX4 Wag,21.0,6.0,160.0,110,3.90,2.875,17.02,0,1,4,4,NaN
2,Datsun 710,22.8,4.0,108.0,93,3.85,2.320,18.61,1,1,4,1,NaN
3,Hornet 4 Drive,21.4,6.0,258.0,110,3.08,3.215,19.44,1,0,3,1,NaN
4,Hornet Sportabout,18.7,8.0,360.0,175,3.15,3.440,17.02,0,0,3,2,NaN
5,Valiant,18.1,NaN,225.0,105,2.76,3.460,20.22,1,0,3,1,NaN
6,Duster 360,14.3,8.0,360.0,245,3.21,3.570,15.84,0,0,3,4,NaN
7,Merc 240D,24.4,4.0,146.7,62,3.69,3.190,20.00,1,0,4,2,NaN
8,Merc 230,22.8,4.0,140.8,95,3.92,3.150,22.90,1,0,4,2,NaN
9,Merc 280,19.2,6.0,167.6,123,3.92,3.440,18.30,1,0,4,4,NaN
10,Merc 280C,17.8,6.0,167.6,123,3.92,3.440,18.90,1,0,4,4,NaN
11,Merc 450SE,16.4,8.0,275.8,180,3.07,4.070,17.40,0,0,3,3,NaN
12,Merc 450SL,17.3,NaN,275.8,180,3.07,3.730,17.60,0,0,3,3,NaN
13,Merc 450SLC,15.2,8.0,275.8,180,3.07,3.780,18.00,0,0,3,3,NaN
14,Cadillac Fleetwood,10.4,8.0,472.0,205,2.93,5.250,17.98,0,0,3,4,14777.0
15,Lincoln Continental,10.4,8.0,460.0,215,3.00,5.424,17.82,0,0,3,4,28388.0
16,Chrysler Imperial,14.7,8.0,440.0,230,3.23,5.345,17.42,0,0,3,4,35077.0
17,Fiat 128,32.4,4.0,78.7,66,4.08,2.200,19.47,1,1,4,1,NaN
18,Honda Civic,30.4,NaN,75.7,52,4.93,1.615,18.52,1,1,4,2,NaN
19,Toyota Corolla,33.9,4.0,71.1,65,4.22,1.835,19.90,1,1,4,1,NaN
20,Toyota Corona,21.5,4.0,120.1,97,3.70,2.465,20.01,1,0,3,1,NaN
21,Dodge Challenger,15.5,8.0,318.0,150,2.76,3.520,16.87,0,0,3,2,72204.0
22,AMC Javelin,15.2,8.0,304.0,150,3.15,3.435,17.30,0,0,3,2,26190.0
23,Camaro Z28,13.3,8.0,350.0,245,3.73,3.840,15.41,0,0,3,4,43894.0
24,Pontiac Firebird,19.2,NaN,400.0,175,3.08,3.845,17.05,0,0,3,2,24977.0
25,Fiat X1-9,27.3,4.0,79.0,66,4.08,1.935,18.90,1,1,4,1,NaN
26,Porsche 914-2,26.0,4.0,120.3,91,4.43,2.140,16.70,0,1,5,2,NaN
27,Lotus Europa,30.4,4.0,95.1,113,3.77,1.513,16.90,1,1,5,2,NaN
28,Ford Pantera L,15.8,8.0,351.0,264,4.22,3.170,14.50,0,1,5,4,NaN
29,Ferrari Dino,19.7,NaN,145.0,175,3.62,2.770,15.50,0,1,5,6,NaN
30,Maserati Bora,15.0,8.0,301.0,335,3.54,3.570,14.60,0,1,5,8,NaN
31,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2,NaN
32,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2,NaN
33,Volvo 142E,21.4,4.0,121.0,109,4.11,2.780,18.60,1,1,4,2,NaN